server:
  port: 9002
  
info:
  component: Zuul Edge Server
  
eureka:
  instance:
    
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
       
  client:
    serviceUrl:
       defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  ignoredServices: "*"
  routes:
    spotparking:
      path: /spotparking/**
      stripPrefix: false
ribbon:
  eureka:
    enabled: true
    readTimeout: 5000
    hystrixTimeout: 4500
    execTime: 4000
    
spotparking:
  ribbon:
    ReadTimeout: 90000  
    ConnectTimeout: 90000  